<?xml version="1.0"?>
<!-- ================================================================================================================================== -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot_leg">
    <xacro:property name="servo_x" value="0.0285"/>
    <xacro:property name="servo_y" value="0.0465"/>
    <xacro:property name="servo_z" value="0.034"/>

<!-- ================================================================================================================================== -->
    <link name="world"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.052 0.096 0.06"/>
            </geometry>
            <origin xyz="0 0 -0.03" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.052 0.096 0.06"/>
            </geometry>
            <origin xyz="0 0 -0.03" rpy="0 0 0"/>
        </collision>
        <xacro:lazy_inertia m="10.0"/>
    </link>
    <joint name="world_base_link" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <link name="main_board">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/_mod_basePlate-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.132 0.036 0.004"/>
            </geometry>
            <origin xyz="0 0.018 0.002" rpy="0 0 0"/>
        </collision>
        <xacro:lazy_inertia m="0.0336"/>
    </link>
    <joint name="base_link_main_board" type="fixed">
        <parent link="base_link"/>
        <child  link="main_board"/>
        <origin xyz="0 0.012 -0.004" rpy="0 0 0"/>
    </joint>

    <!-- ============================================================================================================================== -->
    <link name="servo1_holder">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/_mod_XL-430holderBasic-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
            <origin xyz="0 0 0" rpy="0 0 ${urdf_pi/2}"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.037 0.032 0.014"/>
            </geometry>
            <origin xyz="0 0 0.007" rpy="0 0 ${urdf_pi/2}"/>
        </collision>
        <xacro:box_inertia m="0.0098" x="0.037" y="0.032" z="0.014" o_xyz="0 0 0.007" o_rpy="0 0 ${urdf_pi/2}"/>
    </link> 
    <joint name="main_board_servo1_holder" type="fixed">
        <parent link="main_board"/>
        <child  link="servo1_holder"/>
        <origin xyz="-0.050 0.018 0.004" rpy="0 0 0"/>
    </joint>
    
    <link name="servo1">
        <visual>
            <geometry>
                <box size="${servo_x} ${servo_y} ${servo_z}"/>
            </geometry>
            <origin xyz="0 0 ${servo_y/2}" rpy="${urdf_pi/2} 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${servo_x} ${servo_y} ${servo_z}"/>
            </geometry>
            <origin xyz="0 0 ${servo_y/2}" rpy="${urdf_pi/2} 0 0"/>
        </collision>
        <xacro:box_inertia m="0.0572" x="${servo_x}" y="${servo_y}" z="${servo_z}" o_xyz="0 0 ${servo_y/2}" o_rpy="${urdf_pi/2} 0 0"/>
    </link> 
    <joint name="servo1_holder_servo1" type="fixed">
        <parent link="servo1_holder"/>
        <child  link="servo1"/>
        <origin xyz="0 0 0.008" rpy="0 0 0"/>
    </joint>

    <link name="servo1_padding">
        <visual>
            <geometry>
                <cylinder radius="0.011" length="0.004"/>
            </geometry>
            <origin xyz="0 -0.002 0" rpy="${urdf_pi/2} 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.011" length="0.004"/>
            </geometry>
            <origin xyz="0 -0.002 0" rpy="${urdf_pi/2} 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.0013" r="0.011" l="0.004" o_xyz="0 -0.002 0" o_rpy="${urdf_pi/2} 0 0"/>
    </link> 
    <joint name="servo1_servo1_padding" type="revolute">
        <parent link="servo1"/>
        <child  link="servo1_padding"/>
        <origin xyz="0 ${-servo_z/2-0.002} ${0.01+0.0025/2}" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>
        <limit effort="1000.0" velocity="1.0" lower="2.5" upper="4.0"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <!-- ============================================================================================================================== -->
    <link name="servo2_holder">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/_mod_XL-430holderBasic-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
            <origin xyz="0 0 0" rpy="${urdf_pi/2} 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.037 0.032 0.014"/>
            </geometry>
            <origin xyz="0 -0.007 0" rpy="${urdf_pi/2} 0 0"/>
        </collision>
        <xacro:box_inertia m="0.0098" x="0.037" y="0.032" z="0.014" o_xyz="0 -0.007 0" o_rpy="${urdf_pi/2} 0 0"/>
    </link> 
    <joint name="base_link_servo2_holder" type="fixed">
        <parent link="servo1_padding"/>
        <child  link="servo2_holder"/>
        <origin xyz="0 -0.004 0" rpy="0 0 0"/>
    </joint>
    
    <link name="servo2">
        <visual>
            <geometry>
                <box size="${servo_x} ${servo_y} ${servo_z}"/>
            </geometry>
            <origin xyz="0 ${-servo_y/2} 0" rpy="0 ${urdf_pi/2} 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${servo_x} ${servo_y} ${servo_z}"/>
            </geometry>
            <origin xyz="0 ${-servo_y/2} 0" rpy="0 ${urdf_pi/2} 0"/>
        </collision>
        <xacro:box_inertia m="0.0572" x="${servo_x}" y="${servo_y}" z="${servo_z}" o_xyz="0 ${-servo_y/2} 0" o_rpy="0 ${urdf_pi/2} 0"/>
    </link> 
    <joint name="servo2_holder_servo2" type="fixed">
        <parent link="servo2_holder"/>
        <child  link="servo2"/>
        <origin xyz="0 -0.008 0" rpy="0 0 0"/>
    </joint>

    <link name="servo2_padding">
        <visual>
            <geometry>
                <cylinder radius="0.011" length="0.004"/>
            </geometry>
            <origin xyz="0.002 0 0" rpy="0 ${urdf_pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.011" length="0.004"/>
            </geometry>
            <origin xyz="0.002 0 0" rpy="0 ${urdf_pi/2} 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.0013" r="0.011" l="0.004" o_xyz="0.002 0 0" o_rpy="0 ${urdf_pi/2} 0"/>
    </link> 
    <joint name="servo2_servo2_padding" type="revolute">
        <parent link="servo2"/>
        <child  link="servo2_padding"/>
        <origin xyz="${servo_z/2+0.002} -0.03525 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit effort="1000.0" velocity="1.0" lower="2.0" upper="4.0"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <!-- ============================================================================================================================== -->
    <link name="inner_thigh">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/_mod_thighInner-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="0 0 0" rpy="${-urdf_pi/2} 0 ${-urdf_pi/2}"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.032 0.040 0.006"/>
            </geometry>
            <origin xyz="0.003 -0.016 0" rpy="${-urdf_pi/2} 0 ${-urdf_pi/2}"/>
        </collision>
        <xacro:box_inertia m="0.0085" x="0.040" y="0.032" z="0.006" o_xyz="0.003 -0.016 0" o_rpy="${-urdf_pi/2} 0 ${-urdf_pi/2}"/>
    </link>
    <joint name="servo2_padding_inner_thigh" type="fixed">
        <parent link="servo2_padding"/>
        <child  link="inner_thigh"/>
        <origin xyz="0.004 0.016 0" rpy="0 0 0"/>
    </joint>

    <link name="outer_thigh">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/_mod_thighOuter-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="0 0 0" rpy="${-urdf_pi/2} 0 ${-urdf_pi/2}"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.110 0.040 0.006"/>
            </geometry>
            <origin xyz="0.003 -0.055 0" rpy="${-urdf_pi/2} 0 ${-urdf_pi/2}"/>
        </collision>
        <xacro:box_inertia m="0.0113" x="0.040" y="0.032" z="0.006" o_xyz="0.003 -0.055 0" o_rpy="${-urdf_pi/2} 0 ${-urdf_pi/2}"/>
    </link>
    <joint name="inner_thigh_outer_thigh" type="fixed">
        <parent link="inner_thigh"/>
        <child  link="outer_thigh"/>
        <origin xyz="0.028 0 0" rpy="0 0 0"/>
    </joint>

    <link name="servo3">
        <visual>
            <geometry>
                <box size="${servo_x} ${servo_y} ${servo_z}"/>
            </geometry>
            <origin xyz="0 ${-servo_y/2} 0" rpy="0 ${urdf_pi/2} 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${servo_x} ${servo_y} ${servo_z}"/>
            </geometry>
            <origin xyz="0 ${-servo_y/2} 0" rpy="0 ${urdf_pi/2} 0"/>
        </collision>
        <xacro:box_inertia m="${0.0572+0.0113+0.0078}" x="${servo_x}" y="${servo_y}" z="${servo_z}" 
                           o_xyz="0 ${-servo_y/2} 0" o_rpy="0 ${urdf_pi/2} 0"/>
    </link>
    <joint name="outer_thigh_servo3" type="fixed">
        <parent link="outer_thigh"/>
        <child  link="servo3"/>
        <origin xyz="${servo_y/2-0.006-0.0025} -0.004 0" rpy="0 0 0"/>
    </joint>

    <link name="calfFeet">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/calfFeet-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="purple"/>
            <origin xyz="-0.004 -0.008 0.035" rpy="0 ${urdf_pi/2} 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.150 0.016 0.004"/>
            </geometry>
            <origin xyz="-0.002 ${-0.008+0.008} ${0.035-0.080}" rpy="0 ${-urdf_pi/2} 0"/>
        </collision>
        <xacro:box_inertia m="${0.0251-0.0080}" x="0.150" y="0.016" z="0.004" 
                           o_xyz="${-servo_z/2-0.002-0.0025-0.002} ${-0.008+0.008} ${0.035-0.080}" o_rpy="0 ${-urdf_pi/2} 0"/>
    </link>
    <joint name="servo3_calfFeet" type="revolute">
        <parent link="servo3"/>
        <child  link="calfFeet"/>
        <origin xyz="${-servo_z/2-0.002-0.0025} ${-0.101+0.004} 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>
        <limit effort="1000.0" velocity="1.0" lower="2.0" upper="4.0"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <link name="calfJoint">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/mesh/CADv0/_mod_calfJoint-Body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${urdf_pi/2} 0 ${-urdf_pi/2}"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.022 0.051 0.0065"/>
            </geometry>
            <origin xyz="-0.0005 0 0.0145" rpy="${urdf_pi/2} 0 ${-urdf_pi/2}"/>
        </collision>
        <xacro:box_inertia m="${0.0047+0.0015}" x="0.022" y="0.051" z="0.0065" 
                           o_xyz="-0.0005 0 0.0145" o_rpy="${urdf_pi/2} 0 ${-urdf_pi/2}"/>
    </link>
    <joint name="servo3_calfJoint" type="revolute">
        <parent link="servo3"/>
        <child  link="calfJoint"/>
        <origin xyz="${-servo_z/2-0.002-0.0025} ${-0.01-0.0025/2} 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>
        <mimic joint="servo3_calfFeet" multiplier="1.0" offset="0.0"/>
        <limit effort="1000.0" velocity="1.0" lower="${5*urdf_pi/8}" upper="${11*urdf_pi/8}"/>
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <link name="calfSphere">
        <visual>
            <geometry>
                <sphere radius="0.013"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="dark_purple"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.011"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertia m="0.0080" r="0.011" o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>
    <joint name="calfFeet_calfSphere" type="fixed">
        <parent link="calfFeet"/>
        <child  link="calfSphere"/>
        <origin xyz="-0.002 0.004 ${-0.150+0.035}" rpy="0 0 0"/>
    </joint>
</robot>
<!-- ================================================================================================================================== -->

















